# Generated by Django 4.1.3 on 2022-11-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Portfolio',
        ),
    ]
