# Generated by Django 4.1.3 on 2022-11-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_rename_student_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ism', models.CharField(max_length=50)),
                ('martaba', models.CharField(max_length=50)),
                ('rasmi', models.ImageField(upload_to='media')),
                ('Instagram', models.CharField(max_length=20)),
                ('Twiter', models.CharField(max_length=20)),
                ('Facebok', models.CharField(max_length=50)),
                ('Linced', models.CharField(max_length=50)),
            ],
        ),
    ]
